import type { IRegularizationRequest } from '../types/regularization-types'

export const REGULARIZATION_REQUESTS: IRegularizationRequest[] = [
  {
    createdBy: 'team',
    dates: 'May 22, May 21',
    days: 2,
    employeeName: 'Mugesh Rajapandiyan',
    from: '09:30 am',
    id: 'reg-101',
    manager: 'Asha Menon',
    reason: 'Forgot to check out after client handoff.',
    requestTitle: 'Forgot To Log Out',
    status: 'New Request',
    to: '06:30 pm',
  },
  {
    createdBy: 'team',
    dates: 'May 20',
    days: 1,
    employeeName: 'Leanna Alvord',
    from: '09:40 am',
    id: 'reg-102',
    manager: 'Asha Menon',
    reason: 'Biometric punch was missed during office network downtime.',
    requestTitle: 'Missed Morning Swipe',
    status: 'On Hold',
    to: '06:30 pm',
  },
  {
    createdBy: 'team',
    dates: 'May 18, May 19',
    days: 2,
    employeeName: 'Irina George',
    from: '09:30 am',
    id: 'reg-103',
    manager: 'Mugesh Rajapandiyan',
    reason: 'Manager approved remote work correction.',
    requestTitle: 'Remote Work Correction',
    status: 'Approved',
    to: '06:30 pm',
  },
  {
    createdBy: 'team',
    dates: 'May 16',
    days: 1,
    employeeName: 'Dev Shah',
    from: '10:12 am',
    id: 'reg-104',
    manager: 'Asha Menon',
    reason: 'Insufficient swipe evidence for requested correction.',
    requestTitle: 'Late Swipe Correction',
    status: 'Rejected',
    to: '05:42 pm',
  },
  {
    createdBy: 'team',
    dates: 'May 14, May 15, May 16',
    days: 3,
    employeeName: 'Nikhil Rao',
    from: '09:30 am',
    id: 'reg-105',
    manager: 'Mugesh Rajapandiyan',
    reason: 'Multiple biometric swipes are pending sync.',
    requestTitle: 'Punch Sync Missing',
    status: 'New Request',
    to: '06:30 pm',
  },
  {
    createdBy: 'team',
    dates: 'May 12',
    days: 1,
    employeeName: 'Asha Menon',
    from: '09:22 am',
    id: 'reg-106',
    manager: 'Leanna Alvord',
    reason: 'Correction verified against access logs.',
    requestTitle: 'Office Swipe Correction',
    status: 'Approved',
    to: '06:18 pm',
  },
  {
    createdBy: 'team',
    dates: 'May 09',
    days: 1,
    employeeName: 'Meera Patel',
    from: '09:30 am',
    id: 'reg-107',
    manager: 'Mugesh Rajapandiyan',
    reason: 'Awaiting manager confirmation.',
    requestTitle: 'Shift Time Correction',
    status: 'On Hold',
    to: '06:30 pm',
  },
  {
    createdBy: 'team',
    dates: 'May 07',
    days: 1,
    employeeName: 'Arun Kumar',
    from: '09:30 am',
    id: 'reg-108',
    manager: 'Asha Menon',
    reason: 'Missed punch submitted before payroll sync.',
    requestTitle: 'Forgot To Swipe In',
    status: 'New Request',
    to: '06:30 pm',
  },
  {
    createdBy: 'self',
    dates: 'May 23',
    days: 1,
    employeeName: 'Kishore Kumar DCKAP',
    from: '09:30 am',
    id: 'reg-self-101',
    manager: 'Mugesh Rajapandiyan',
    reason: 'Forgot to log out after late production support.',
    requestTitle: 'Forgot To Log Out',
    status: 'New Request',
    to: '06:30 pm',
  },
  {
    createdBy: 'self',
    dates: 'May 19',
    days: 1,
    employeeName: 'Kishore Kumar DCKAP',
    from: '09:20 am',
    id: 'reg-self-102',
    manager: 'Mugesh Rajapandiyan',
    reason: 'Attendance corrected and approved by reporting manager.',
    requestTitle: 'Missing Swipe Correction',
    status: 'Approved',
    to: '06:10 pm',
  },
]
